// Generated by CoffeeScript 2.1.1
(function() {
  var fns;

  fns = {};

  fns.ran = function(r) {
    return r[Math.floor(Math.random() * r.length)];
  };

  fns.isnul = function(t) {
    return Math.abs(t) < 0.001;
  };

  window.fns = fns;

}).call(this);
